<?php

namespace Database\Seeders;

use App\Models\CityArea;
use App\Models\CityCorporation;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CityAreaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $cityAreas = [
            'Dhaka North City Corporation (DNCC)' => [
                'Uttara',
                'Mirpur',
                'Gulshan',
                'Banani',
                'Badda',
                'Mohakhali',
                'Baridhara',
                'Niketon',
                'Khilkhet',
                'Cantonment',
                'Kuril',
                'Vatara',
                'Adabor',
                'Shewrapara',
                'Agargaon',
                'Kazipara',
                'Darussalam',
                'Kafrul',
                'Uttarkhan',
                'Pallabi',
                'Nikunja',
                'Bashundhara R/A',
                'Tongi',
                'Kakrail',
                'Shyamoli',
                'Dhamrai',
                'Mohakhali DOHS',
                'Rampura',
                'Mirpur DOHS',
                'Mirpur Cantonment',
                'Shah Ali',
                'Rayer Bazar',
                'Farmgate',
                'Kamalapur',
                'Elephant Road',
                'Lalmatia',
                'Malibagh',
                'Tejgaon',
                'Sher-e-Bangla Nagar',
                'Gabtoli',
                'Rupnagar',
                'Mirpur-1',
                'Mirpur-2',
                'Mirpur-6',
                'Mirpur-7',
                'Mirpur-10',
                'Mirpur-11',
                'Mirpur-12',
                'Mirpur-13',
                'Mirpur-14',
            ],

            'Dhaka South City Corporation (DSCC)' => [
                'Dhanmondi',
                'Mohammadpur',
                'Lalbagh',
                'Kotwali',
                'Shahbag',
                'Armanitola',
                'Shyampur',
                'Demra',
                'Laxmibazar',
                'Gendaria',
                'Wari',
                'Sutrapur',
                'Kamrangirchar',
                'Kotwali Police Line',
                'Bangshal',
                'Chawkbazar',
                'Nayabazar',
                'Nababganj',
                'Banglamotor',
                'Fakirapool',
                'Shantinagar',
                'Moghbazar',
                'Gulshan Model Town',
                'Banani',
                'Baridhara',
                'Bashundhara',
                'Kakrail',
                'Malibagh',
                'Mouchak',
                'Siddheshwari',
                'Jatrabari',
                'Jurain',
                'Dholpur',
                'Posta',
                'Dhaka Cantonment',
                'Mirpur Cantonment',
                'Uttar Khan',
                'Darus Salam',
                'Khilkhet',
                'Nikunja',
                'Airport',
                'Rampura Bazar',
                'Middle Badda',
                'Banasree Block-C',
                'North Badda',
                'Postogola',
                'Dakshinkhan',
                'Nawabganj',
                'Jhigatola',
                'Pallabi Extension',
                'Uttara',
                'Mohakhali',
                'Badda',
                'Basabo',
                'Merul Badda',
                'Bashabo',
                'Shantibagh',
                'Basundhara Residential Area',
                'Mohammadpur Housing',
                'Green Road',
                'Mohammadpur Krishi Market',
                'Tikatuli',
                'Kamalapur',
                'Basundhara R/A',
                'Shantibagh R/A',
                'Monipur',
                'Rayer Bazar',
                'Baily Road',
                'Elephant Road',
                'New Market',
                'Hatirpool',
                'Panthapath',
                'Zigatola',
                'Badda Link Road',
                'South Mugda',
                'Notun Bazar',
                'Malibagh Chowdhurypara',
                'Kadamtoli',
                'Khilgaon',
                'Shampur',
                'Malibagh Rail Gate',
                'Bongshal',
                'Motijheel',
                'Tanti Bazar',
                'Rupnagar',
                'Nayatola',
                'Khilgaon Taltola',
                'Bijoynagar',
                'Islampur',
                'Kalabagan',
                'Agargaon',
            ],
        ];

        foreach ($cityAreas as $corpsName => $areas) {
            $corp = CityCorporation::where('name', $corpsName)->first();

            if (!$corp) continue;

            foreach ($areas as $area) {
                CityArea::firstOrCreate([
                    'city_corporation_id' => $corp->id,
                    'name' => $area,
                ]);
            }
        }
    }
}
