<?php

namespace Database\Seeders;

use App\Models\District;
use App\Models\Upazilla;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class UpazillaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $districtUpazilas = [
            'Bagerhat' => [
                'Bagerhat Sadar',
                'Chitalmari',
                'Fakirhat',
                'Kachua',
                'Mollahat',
                'Mongla',
                'Morrelganj',
                'Rampal',
                'Sarankhola',
            ],
            'Bandarban' => [
                'Ali kadam',
                'Bandarban Sadar',
                'Lama',
                'Naikhongchhari',
                'Rowangchhari',
                'Ruma',
                'Thanchi',
            ],
            'Barguna' => [
                'Amtali',
                'Bamna',
                'Barguna Sadar',
                'Betagi',
                'Patharghata',
                'Taltali',
            ],
            'Barishal' => [
                'Agailjhara',
                'Babuganj',
                'Bakerganj',
                'Banaripara',
                'Barisal Sadar',
                'Gaurnadi',
                'Hizla',
                'Mehendiganj',
                'Muladi',
                'Wazirpur',
            ],
            'Bhola' => [
                'Bhola Sadar',
                'Burhanuddin',
                'Char Fasson',
                'Daulatkhan',
                'Lalmohan',
                'Manpura',
                'Tazumuddin',
            ],
            'Bogura' => [
                'Adamdighi',
                'Bogra Sadar',
                'Dhunat',
                'Dhupchanchia',
                'Gabtali',
                'Kahaloo',
                'Nandigram',
                'Sariakandi',
                'Shahajanpur',
                'Sherpur',
                'Shibganj',
                'Sonatala',
            ],
            'Brahmanbaria' => [
                'Akhaura',
                'Ashuganj',
                'Bancharampur',
                'Brahmanbaria Sadar',
                'Kasba',
                'Nabinagar',
                'Nasirnagar',
                'Sarail',
                'Shahbazpur Town',
                'Bijoynagar',
            ],
            'Chandpur' => [
                'Chandpur Sadar',
                'Faridganj',
                'Haimchar',
                'Haziganj',
                'Kachua',
                'Matlab Dakkhin',
                'Matlab Uttar',
                'Shahrasti',
            ],
            'Chapainawabganj' => [
                'Bholahat',
                'Gomastapur',
                'Nachole',
                'Nawabganj Sadar',
                'Shibganj',
            ],
            'Chattogram' => [
                'Anwara',
                'Banshkhali',
                'Boalkhali',
                'Chandanaish',
                'Fatikchhari',
                'Hathazari',
                'Lohagara',
                'Mirsharai',
                'Patiya',
                'Rangunia',
                'Raozan',
                'Sandwip',
                'Satkania',
                'Sitakunda',
            ],
            'Chuadanga' => [
                'Alamdanga',
                'Chuadanga Sadar',
                'Damurhuda',
                'Jibannagar',
            ],
            'Cumilla' => [
                'Barura',
                'Brahmanpara',
                'Burichong',
                'Chandina',
                'Chauddagram',
                'Comilla Sadar',
                'Comilla Sadar South',
                'Daudkandi',
                'Debidwar',
                'Homna',
                'Laksam',
                'Meghna',
                'Monohorgonj',
                'Muradnagar',
                'Nangalkot',
                'Titas',
            ],
            "Cox's Bazar" => [
                'Chakaria',
                'Cox\'s Bazar Sadar',
                'Eidgaon',
                'Kutubdia',
                'Maheshkhali',
                'Pekua',
                'Ramu',
                'Teknaf',
                'Ukhia',
            ],
            'Dhaka' => [
                'City Corporation',
                'Dhamrai',
                'Dohar',
                'Keraniganj',
                'Nawabganj',
                'Savar',
            ],
            'Dinajpur' => [
                'Birampur',
                'Birganj',
                'Biral',
                'Bochaganj',
                'Chirirbandar',
                'Dinajpur Sadar',
                'Ghoraghat',
                'Hakimpur',
                'Kaharole',
                'Khansama',
                'Nawabganj',
                'Parbatipur',
                'Phulbari',
            ],
            'Faridpur' => [
                'Alfadanga',
                'Bhanga',
                'Boalmari',
                'Charbhadrasan',
                'Faridpur Sadar',
                'Madhukhali',
                'Nagarkanda',
                'Sadarpur',
                'Shaltha',
            ],
            'Feni' => [
                'Chagalnaiya',
                'Daganbhyan',
                'Feni Sadar',
                'Fhulgazi',
                'Parshuram',
                'Sonagazi',
            ],
            'Gaibandha' => [
                'Fulchhari',
                'Gaibandha Sadar',
                'Gobindaganj',
                'Palashbari',
                'Sadullapur',
                'Saghata',
                'Sundarganj',
            ],
            'Gazipur' => [
                'Gazipur Sadar',
                'Kaliakior',
                'Kaliganj',
                'Kapasia',
                'Sripur',
                'Tongi',
            ],
            'Gopalganj' => [
                'Gopalganj Sadar',
                'Kashiani',
                'Kotalipara',
                'Muksudpur',
                'Tungipara',
            ],
            'Habiganj' => [
                'Ajmiriganj',
                'Bahubal',
                'Baniachang',
                'Chunarughat',
                'Habiganj Sadar',
                'Lakhai',
                'Madhabpur',
                'Nabiganj',
                'Shaistagonj',
            ],
            'Jamalpur' => [
                'Baksiganj',
                'Dewanganj',
                'Islampur',
                'Jamalpur Sadar',
                'Madarganj',
                'Melandaha',
                'Narundi Police I.C',
                'Sarishabari',
            ],
            'Jashore' => [
                'Abhaynagar',
                'Bagherpara',
                'Chaugachha',
                'Jhikargachha',
                'Keshabpur',
                'Jessore Sadar',
                'Manirampur',
                'Sharsha',
            ],
            'Jhalokati' => [
                'Jhalokati Sadar',
                'Kathalia',
                'Nalchity',
                'Rajapur',
            ],
            'Jhenaidah' => [
                'Harinakunda',
                'Jhenaidah Sadar',
                'Kaliganj',
                'Kotchandpur',
                'Maheshpur',
                'Shailkupa',
            ],
            'Joypurhat' => [
                'Akkelpur',
                'Joypurhat Sadar',
                'Kalai',
                'Khetlal',
                'Panchbibi',
            ],
            'Khagrachhari' => [
                'Dighinala',
                'Khagrachhari Sadar',
                'Lakshmichhari',
                'Mahalchhari',
                'Manikchhari',
                'Matiranga',
                'Panchhari',
                'Ramgarh',
            ],
            'Khulna' => [
                'Batiaghata',
                'Dacope',
                'Dighalia',
                'Dumuria',
                'Koyra',
                'Paikgachha',
                'Phultala',
                'Rupsa',
                'Terokhada',
            ],
            'Kishoreganj' => [
                'Astagram',
                'Bajitpur',
                'Bhairab',
                'Hossainpur',
                'Itna',
                'Karimganj',
                'Katiadi',
                'Kishoreganj Sadar',
                'Kuliarchar',
                'Mithamain',
                'Nikli',
                'Pakundia',
                'Tarail',
            ],
            'Kurigram' => [
                'Bhurungamari',
                'Char Rajibpur',
                'Chilmari',
                'Kurigram Sadar',
                'Nageshwari',
                'Phulbari',
                'Rajarhat',
                'Raumari',
                'Ulipur',
            ],
            'Kushtia' => [
                'Bheramara',
                'Daulatpur',
                'Khoksa',
                'Kumarkhali',
                'Kushtia Sadar',
                'Mirpur',
            ],
            'Lakshmipur' => [
                'Lakshmipur Sadar',
                'Raipur',
                'Ramganj',
                'Ramgati',
                'Komol Nagar',
            ],
            'Lalmonirhat' => [
                'Aditmari',
                'Hatibandha',
                'Kaliganj',
                'Lalmonirhat Sadar',
                'Patgram',
            ],
            'Madaripur' => [
                'Dasar',
                'Kalkini',
                'Madaripur Sadar',
                'Rajoir',
                'Shibchar',
            ],
            'Magura' => [
                'Magura Sadar',
                'Mohammadpur',
                'Shalikha',
                'Sreepur',
            ],
            'Manikganj' => [
                'Daulatpur',
                'Ghior',
                'Harirampur',
                'Manikganj Sadar',
                'Saturia',
                'Shibalaya',
                'Singair',
            ],
            'Meherpur' => [
                'Meherpur Sadar',
                'Mujib Nagar',
                'Angni',
            ],
            'Moulvibazar' => [
                'Barlekha',
                'Juri',
                'Kamalganj',
                'Kulaura',
                'Moulvibazar Sadar',
                'Rajnagar',
                'Sreemangal',
            ],
            'Munshiganj' => [
                'Gazaria',
                'Lohajang',
                'Munshiganj Sadar',
                'Sirajdikhan',
                'Sreenagar',
                'Tongibari',
            ],
            'Mymensingh' => [
                'Bhaluka',
                'Dhobaura',
                'Fulbaria',
                'Gaffargaon',
                'Gauripur',
                'Haluaghat',
                'Ishwarganj',
                'Muktagachha',
                'Mymensingh Sadar',
                'Nandail',
                'Phulpur',
                'Trishal',
            ],
            'Naogaon' => [
                'Atrai',
                'Badalgachhi',
                'Dhamoirhat',
                'Manda',
                'Mohadevpur',
                'Naogaon Sadar',
                'Niamatpur',
                'Patnitala',
                'Porsha',
                'Raninagar',
                'Sapahar',
            ],
            'Narail' => [
                'Kalia',
                'Lohagara',
                'Narail Sadar',
            ],
            'Narayanganj' => [
                'Araihazar',
                'Bandar',
                'Narayanganj Sadar',
                'Rupganj',
                'Siddirgonj',
                'Sonargaon',
            ],
            'Narsingdi' => [
                'Belabo',
                'Monohardi',
                'Narsingdi Sadar',
                'Palash',
                'Raipura',
                'Shibpur',
            ],
            'Natore' => [
                'Bagatipara',
                'Baraigram',
                'Gurudaspur',
                'Lalpur',
                'Natore Sadar',
                'Singra',
            ],
            'Netrokona' => [
                'Atpara',
                'Barhatta',
                'Durgapur',
                'Kalmakanda',
                'Kendua',
                'Khaliajuri',
                'Madan',
                'Mohanganj',
                'Netrokona Sadar',
                'Purbadhala',
            ],
            'Nilphamari' => [
                'Dimla',
                'Domar',
                'Jaldhaka',
                'Kishoreganj',
                'Nilphamari Sadar',
                'Saidpur',
            ],
            'Noakhali' => [
                'Begumganj',
                'Chatkhil',
                'Companyganj',
                'Hatia',
                'Kabirhat',
                'Noakhali Sadar',
                'Senbagh',
                'Sonaimuri',
                'Suborno Char',
            ],
            'Pabna' => [
                'Atgharia',
                'Bera',
                'Bhangura',
                'Chatmohar',
                'Faridpur',
                'Ishwardi',
                'Pabna Sadar',
                'Santhia',
                'Sujanagar',
            ],
            'Panchagarh' => [
                'Atwari',
                'Boda',
                'Debiganj',
                'Panchagarh Sadar',
                'Tetulia',
            ],
            'Patuakhali' => [
                'Bauphal',
                'Dashmina',
                'Dumki',
                'Galachipa',
                'Kalapara',
                'Mirzaganj',
                'Patuakhali Sadar',
                'Rangabali',
            ],
            'Pirojpur' => [
                'Bhandaria',
                'Kaukhali',
                'Mathbaria',
                'Nazirpur',
                'Nesarabad',
                'Pirojpur Sadar',
                'Zianagar',
            ],
            'Rajbari' => [
                'Baliakandi',
                'Goalandaghat',
                'Kalukhali',
                'Pangsha',
                'Rajbari Sadar',
            ],
            'Rajshahi' => [
                'Bagha',
                'Bagmara',
                'Charghat',
                'Durgapur',
                'Godagari',
                'Mohanpur',
                'Paba',
                'Puthia',
                'Tanore',
            ],
            'Rangamati' => [
                'Bagaichhari',
                'Barkal',
                'Kaukhali',
                'Kaptai',
                'Juraichhari',
                'Langadu',
                'Nannerchar',
                'Rajasthali',
                'Rangamati Sadar',
            ],
            'Rangpur' => [
                'Badarganj',
                'Gangachara',
                'Kaunia',
                'Mithapukur',
                'Pirgachha',
                'Pirganj',
                'Rangpur Sadar',
                'Taraganj',
            ],
            'Satkhira' => [
                'Assasuni',
                'Debhata',
                'Kalaroa',
                'Kaliganj',
                'Satkhira Sadar',
                'Shyamnagar',
                'Tala',
            ],
            'Shariatpur' => [
                'Bhedarganj',
                'Damudya',
                'Gosairhat',
                'Jajira',
                'Naria',
                'Shariatpur Sadar',
            ],
            'Sherpur' => [
                'Jhenaigati',
                'Nakla',
                'Nalitabari',
                'Sherpur Sadar',
                'Sreebardi',
            ],
            'Sirajganj' => [
                'Belkuchi',
                'Chauhali',
                'Kamarkhanda',
                'Kazipur',
                'Raiganj',
                'Shahjadpur',
                'Sirajganj Sadar',
                'Tarash',
                'Ullahpara',
            ],
            'Sunamganj' => [
                'Bishwamvarpur',
                'Chhatak',
                'Derai',
                'Dharampasha',
                'Dowarabazar',
                'Jagannathpur',
                'Jamalganj',
                'Modhyanagar',
                'Shanthiganj',
                'Sulla',
                'Sunamganj Sadar',
                'Tahirpur',
            ],
            'Sylhet' => [
                'Balaganj',
                'Beanibazar',
                'Bishwanath',
                'Companiganj',
                'Dakshin Surma',
                'Fenchuganj',
                'Golapganj',
                'Gowainghat',
                'Jointapur',
                'Kanaighat',
                'Sylhet Sadar',
                'Zakiganj',
            ],
            'Tangail' => [
                'Basail',
                'Bhuapur',
                'Delduar',
                'Dhanbari',
                'Ghatail',
                'Gopalpur',
                'Kalihati',
                'Madhupur',
                'Mirzapur',
                'Nagarpur',
                'Sakhipur',
                'Tangail Sadar',
            ],
            'Thakurgaon' => [
                'Baliadangi',
                'Haripur',
                'Pirganj',
                'Ranisankail',
                'Thakurgaon Sadar',
            ],
        ];

        foreach ($districtUpazilas as $districtName => $upazillaList) {
            $district = District::where('name', $districtName)->first();

            if (!$district) continue;

            foreach ($upazillaList as $upazila) {
                $name = trim($upazila);
                if ($upazila == '') continue;
                Upazilla::firstOrCreate(
                    ['district_id' => $district->id, 'name' => $upazila],
                    ['district_id' => $district->id, 'name' => $upazila]
                );
            }
        }
    }
}
